
meta_product_name: "7thAD"
meta_title: "7thAD - Interagissez avec votre audience"
meta_description: "7thAD crée une expérience inédite autour de vos couleurs et de votre positionnement"
meta_image: "demo-day.png"                       # should exist in `app/assets/images/`
  # required for Twitter Cards
